apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-xfce
  namespace: $NAMESPACE
  labels:
    app: webtop
    type: debian-xfce
spec:
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: debian-xfce
          image: lscr.io/linuxserver/webtop:debian-xfce
          securityContext:
            privileged: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: SUBFOLDER
              value: "/"
            - name: TITLE
              value: "HAW Development Desktop"
            # Installation der Entwicklungstools
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-package-install"
            - name: INSTALL_PACKAGES
              value: "code sublime-text conky ansible git curl wget xdg-utils gnupg2 apt-transport-https software-properties-common build-essential python3-pip"
            # Wenn Sie ein Passwort setzen wollen (empfohlen)
            - name: PASSWORD
              value: "$VNC_PASSWORD"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    # Warte bis apt verfügbar ist
                    until apt-get update; do sleep 2; done
                    
                    # Füge VSCode Repository hinzu (falls nicht durch universal-package-install installiert)
                    if ! dpkg -l code > /dev/null 2>&1; then
                      wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/microsoft.gpg
                      install -o root -g root -m 644 /tmp/microsoft.gpg /etc/apt/trusted.gpg.d/
                      echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
                      apt-get update && apt-get install -y code
                    fi
                    
                    # Füge Sublime Text Repository hinzu (falls nicht durch universal-package-install installiert)
                    if ! dpkg -l sublime-text > /dev/null 2>&1; then
                      wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
                      echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
                      apt-get update && apt-get install -y sublime-text
                    fi
                    
                    # Füge Ansible Repository hinzu (falls nicht durch universal-package-install installiert)
                    if ! dpkg -l ansible > /dev/null 2>&1; then
                      apt-get update && apt-get install -y software-properties-common
                      apt-add-repository --yes --update ppa:ansible/ansible
                      apt-get install -y ansible
                    fi
                    
                    # Erstelle Desktop-Shortcuts
                    mkdir -p /config/home/abc/Desktop
                    
                    # VSCode Desktop-Shortcut
                    cat > /config/home/abc/Desktop/vscode.desktop << EOL
                    [Desktop Entry]
                    Name=Visual Studio Code
                    Comment=Code Editing. Redefined.
                    GenericName=Text Editor
                    Exec=/usr/bin/code --no-sandbox
                    Icon=vscode
                    Type=Application
                    StartupNotify=true
                    Categories=Utility;TextEditor;Development;IDE;
                    EOL
                    
                    # Sublime Text Desktop-Shortcut
                    cat > /config/home/abc/Desktop/sublime-text.desktop << EOL
                    [Desktop Entry]
                    Name=Sublime Text
                    Comment=Sophisticated text editor for code, markup and prose
                    Exec=/usr/bin/subl
                    Icon=sublime-text
                    Type=Application
                    Terminal=false
                    Categories=TextEditor;Development;
                    EOL
                    
                    # Ansible Desktop-Shortcut
                    cat > /config/home/abc/Desktop/ansible-terminal.desktop << EOL
                    [Desktop Entry]
                    Name=Ansible Terminal
                    Comment=Open Terminal with Ansible
                    Exec=xfce4-terminal --command="bash -c 'echo \"Welcome to Ansible Terminal. Run ansible --version to verify installation.\"; bash'"
                    Icon=utilities-terminal
                    Type=Application
                    Terminal=false
                    Categories=Development;System;
                    EOL
                    
                    # Firefox für Docs Desktop-Shortcut
                    cat > /config/home/abc/Desktop/documentation.desktop << EOL
                    [Desktop Entry]
                    Name=Development Docs
                    Comment=Access documentation in Firefox
                    Exec=firefox https://code.visualstudio.com/docs https://docs.ansible.com https://www.sublimetext.com/docs/
                    Icon=firefox
                    Type=Application
                    Terminal=false
                    Categories=Network;WebBrowser;
                    EOL
                    
                    # Setze richtige Berechtigungen
                    chmod +x /config/home/abc/Desktop/*.desktop
                    chown -R abc:abc /config/home/abc
                    
                    # Set-up für Multi-Plattform-Zugriff
                    apt-get install -y firefox remmina vinagre freerdp2-x11 tigervnc-viewer
                    
                    # Schreibe eine README-Datei mit Zugriffsinformationen
                    cat > /config/home/abc/Desktop/README.txt << EOL
                    HAW Development Desktop - Zugriffsinformationen
                    
                    == Browser-Zugriff ==
                    Zugriff über jeden modernen Browser: http://localhost:3000 oder https://localhost:3001
                    
                    == Native Clients ==
                    Windows: Microsoft Remote Desktop, VNC Viewer, oder NoMachine
                    macOS: Microsoft Remote Desktop, VNC Viewer, oder NoMachine
                    Linux: Remmina, Vinagre, TigerVNC, oder NoMachine
                    
                    == Dateiaustausch ==
                    - Über Browser-Upload/Download
                    - Über SFTP (wenn konfiguriert)
                    - Über Shared Folders (wenn konfiguriert)
                    
                    Weitere Informationen: Siehe Dokumentation im Git-Repository
                    EOL
          resources:
            limits:
              memory: "$MEMORY_LIMIT"
              cpu: "$CPU_LIMIT"
          volumeMounts:
            - name: webtop-data
              mountPath: /config
      volumes:
        - name: webtop-data
          persistentVolumeClaim:
            claimName: webtop-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-pvc
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: "$STORAGE_SIZE"
---
apiVersion: v1
kind: Service
metadata:
  name: debian-xfce
  namespace: $NAMESPACE
  labels:
    app: webtop
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: webtop
  type: ClusterIP