apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-xfce
  namespace: $NAMESPACE
  labels:
    service: webtop
spec:
  selector:
    matchLabels:
      service: webtop
  template:
    metadata:
      labels:
        service: webtop
    spec:
      containers:
        - image: lscr.io/linuxserver/webtop:debian-xfce
          name: debian-xfce
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: SUBFOLDER
              value: "/"
            - name: TITLE
              value: "HAW Development Desktop"
            - name: PASSWORD
              value: "$VNC_PASSWORD"
          volumeMounts:
            - mountPath: "/config"
              name: webtop-volume
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 3001
              name: https
            - containerPort: 5900
              name: vnc
              protocol: TCP
          resources:
            limits:
              memory: "$MEMORY_LIMIT"
              cpu: "$CPU_LIMIT"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    # Robuster Update-Prozess
                    echo "Aktualisiere Paketlisten..."
                    apt-get update || (sleep 10 && apt-get update) || (sleep 30 && apt-get update)
                    
                    # Notwendige Tools für Repositories installieren
                    echo "Installiere grundlegende Tools..."
                    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common
                    
                    # Microsoft Repository für VS Code hinzufügen
                    echo "Füge VS Code Repository hinzu..."
                    curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg
                    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
                    
                    # Sublime Text Repository hinzufügen
                    echo "Füge Sublime Text Repository hinzu..."
                    curl -sSL https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor > /usr/share/keyrings/sublime-text-archive-keyring.gpg
                    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/sublime-text-archive-keyring.gpg] https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
                    
                    # Ansible Repository hinzufügen
                    echo "Füge Ansible Repository hinzu..."
                    add-apt-repository --yes --update ppa:ansible/ansible
                    
                    # Update nach Hinzufügen der Repositories
                    echo "Aktualisiere Paketlisten nach Hinzufügen der Repositories..."
                    apt-get update
                    
                    # Pakete installieren
                    echo "Installiere Firefox und Terminal..."
                    apt-get install -y xfce4-terminal firefox
                    
                    echo "Installiere Entwicklungstools..."
                    apt-get install -y git wget curl xdg-utils build-essential python3-pip
                    apt-get install -y code sublime-text ansible
                    
                    # Desktop-Verzeichnis erstellen falls nicht vorhanden
                    echo "Erstelle Desktop-Verknüpfungen..."
                    mkdir -p /config/Desktop
                    
                    # VSCode Desktop-Shortcut
                    cat > /config/Desktop/vscode.desktop << EOL
                    [Desktop Entry]
                    Name=Visual Studio Code
                    Comment=Code Editing. Redefined.
                    GenericName=Text Editor
                    Exec=/usr/bin/code --no-sandbox
                    Icon=vscode
                    Type=Application
                    StartupNotify=true
                    Categories=Utility;TextEditor;Development;IDE;
                    EOL
                    
                    # Sublime Text Desktop-Shortcut
                    cat > /config/Desktop/sublime-text.desktop << EOL
                    [Desktop Entry]
                    Name=Sublime Text
                    Comment=Sophisticated text editor for code, markup and prose
                    Exec=/usr/bin/subl
                    Icon=sublime-text
                    Type=Application
                    Terminal=false
                    Categories=TextEditor;Development;
                    EOL
                    
                    # Ansible Desktop-Shortcut
                    cat > /config/Desktop/ansible-terminal.desktop << EOL
                    [Desktop Entry]
                    Name=Ansible Terminal
                    Comment=Open Terminal with Ansible
                    Exec=xfce4-terminal --command="bash -c 'echo \"Welcome to Ansible Terminal. Run ansible --version to verify installation.\"; bash'"
                    Icon=utilities-terminal
                    Type=Application
                    Terminal=false
                    Categories=Development;System;
                    EOL
                    
                    # Berechtigungen setzen
                    chmod +x /config/Desktop/*.desktop
                    chown -R abc:abc /config
                    
                    # Statusdatei erstellen
                    echo "Installation abgeschlossen am $(date)" > /config/installation_complete.txt
      volumes:
        - name: webtop-volume
          persistentVolumeClaim:
            claimName: webtop-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: debian-xfce
  namespace: $NAMESPACE
  labels:
    service: webtop
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 3001
      protocol: TCP
      targetPort: 3001
    - name: vnc
      port: 5900
      protocol: TCP
      targetPort: 6901
  selector:
    service: webtop
  type: ClusterIP